<!DOCTYPE html>
<html lang="en" class="h-full">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $this->section('title') ?></title>

    <?= $this->section('meta') ?>

    <?php if ($config['app']['env'] === 'development') : ?>
        <!-- vite -->
        <script type="module" src="http://localhost:5173/@vite/client"></script>
        <script type="module" src="http://localhost:5173/resources/js/app.js"></script>
    <?php else: ?>
        <!-- build -->
        <link rel="stylesheet" href="/css/app.css">
        <script src="/js/app.js" defer></script>
    <?php endif ?>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3" />
    <script src="https://cdn.jsdelivr.net/npm/@docsearch/js@3"></script>
</head>

<body class="h-full bg-white dark:bg-gray-900">
    <!-- Navigation -->
    <?= $this->insert('partials/navigation', ['config' => $config]) ?>

    <!-- Sidebar -->
    <?= $this->insert('partials/sidebar', ['config' => $config]) ?>

    <!-- Main content -->
    <div class="p-4 lg:ml-64 mt-14">
        <div class="p-4 mx-auto max-w-4xl">
            <article class="prose dark:prose-invert max-w-none">
                <?= $this->section('content') ?>
            </article>
        </div>
    </div>

    <!-- Footer -->
    <?= $this->insert('partials/footer', ['config' => $config]) ?>
</body>

</html>