<!DOCTYPE html>
<html lang="<?= $locale ?>">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>404 - <?= __('Not Found') ?></title>
    <?php if ($config['app']['env'] === 'development') : ?>
        <!-- vite -->
        <script type="module" src="http://localhost:5173/@vite/client"></script>
        <script type="module" src="http://localhost:5173/resources/js/app.js"></script>
    <?php else: ?>
        <!-- build -->
        <link rel="stylesheet" href="/css/app.css">
        <script src="/js/app.js" defer></script>
    <?php endif ?>
</head>

<body class="h-full bg-white dark:bg-gray-900">
    <main class="grid min-h-screen place-items-center px-6 py-24 sm:py-32 lg:px-8">
        <div class="text-center">
            <p class="text-8xl font-semibold text-indigo-600 dark:text-indigo-400">404</p>
            <h1 class="mt-4 text-3xl font-bold tracking-tight text-gray-900 dark:text-white sm:text-5xl"><?= __('Not Found') ?></h1>
            <p class="mt-6 text-base leading-7 text-gray-600 dark:text-gray-400">Sorry, we couldn't find the page you're looking for.</p>
            <div class="mt-10 flex items-center justify-center gap-x-6">
                <a href="javascript:history.back()" class="text-sm font-semibold text-gray-900 dark:text-white hover:text-indigo-500 dark:hover:text-indigo-400">
                    <span aria-hidden="true">&larr;</span> Go back
                </a>
                <a href="/" class="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Go back home</a>
            </div>
        </div>
    </main>
</body>

</html>