<div class="flex gap-8">
    <div class="flex-1">
        <div class="mb-4">
            <h1 class="text-4xl font-bold tracking-tight text-gray-900 dark:text-white"><?= $title ?></h1>
        </div>

        <!-- edit this page -->
        <div class="mb-4">
            <a href="<?= $config['app']['docs_github'] ?>/edit/main/docs/<?= $locale ?>/content/<?= $slug ?>.md" class="inline-flex items-center text-sm text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-white">
                <svg class="w-4 h-4 mr-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                    <path d="M17.414 2.586a2 2 0 00-2.828 0L7 10.172V13h2.828l7.586-7.586a2 2 0 000-2.828z"></path>
                    <path fill-rule="evenodd" d="M2 6a2 2 0 012-2h4a1 1 0 010 2H4v10h10v-4a1 1 0 112 0v4a2 2 0 01-2 2H4a2 2 0 01-2-2V6z" clip-rule="evenodd"></path>
                </svg>
                Edit on GitHub
            </a>
        </div>

        <div class="markdown-content prose dark:prose-invert max-w-none prose-lg prose-slate">
            <?= $content ?>
        </div>
    </div>

    <div class="w-64 shrink-0">
        <div class="fixed">
            <?= $this->insert('partials/toc', ['toc' => $toc]) ?>
        </div>
    </div>
</div>