<div class="mb-8">
    <h1 class="text-4xl font-bold tracking-tight text-gray-900 dark:text-white"><?= $title ?></h1>
</div>

<div class="markdown-content prose dark:prose-invert max-w-none prose-lg prose-slate">
    <?= $content ?>
</div>

<!-- edit this page -->
<a href="<?= $config['app']['docs_github'] ?>/edit/main/docs/<?= $path ?>" class="text-blue-500 hover:text-blue-700">Edit this page on GitHub</a>